### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by WEBMASTERSMEX** [a-chris/medium-no-thanks#1]
Opens blank doesn't show anything. After installing and opening is there something else I have to do to see content?

**Comment by a-chris** [comment]
Sorry for the issue, I will add a few instructions in the next release.

1. Read articles using the Medium application
2. If you find an article with paywall click to share it
3. Select Medium No Thanks from the sharesheet

**New version 1.0.1 released with few instructions**
