### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BrajBliss** [a-chris/medium-no-thanks#2]
Is it possible to add clapping ability in there? I get it it's just a webview, but maybe if users can sign in or it can use the default medium app sign in account to clap and all.

`//Nevermind I am not asking for a standalone app, it could be possible just by using web2apk but medium's android app is silly and feature less//`

**Comment by a-chris** [comment]
Hi @kkrrssnnaa, I'm sorry but this is probably impossible.
Looking at the [Medium API documentation](https://github.com/Medium/medium-api-docs) I don't see any way to clap an article, furthermore it won't work because using a sign in would break the trick to bypass the paywall.

**Comment by kkrrssnnaa** [comment]
@a-chris gotcha. But still, quick & fun solution to use. Heads up Man!
