### ISSUE TITLE
Integrate Android app links

### ISSUE THREAD

**Issue by eliasfloreteng** [a-chris/medium-no-thanks#7]
As a feature suggestion, you could implement Android app links so it automatically opens the app when clicking on a medium.com link.

**Comment by a-chris** [comment]
thanks for the suggestion, I'm working on it 😊

**Comment by a-chris** [comment]
I've added this feature in the 1.3.0 version, you can download it [here](https://github.com/a-chris/medium-no-thanks/releases/tag/1.3.0)

**Comment by eliasfloreteng** [comment]
Thank you! 🙏
Just a small note, it would be nice if custom medium urls worked.
Here are some of them that i noted down:
- https://towardsdatascience.com/
- https://uxdesign.cc/
- https://betterprogramming.pub/
- https://plainenglish.io/
- https://uxplanet.org/

(It would've been smarter to say this _before_ you implemented it, sorry)

**Comment by eliasfloreteng** [comment]
I've made a pull request with the changes, although I am not a android developer so you may need to change it.

#9

**Comment by a-chris** [comment]
It is already working for me with these urls, except the first, does not work for you?
Can I ask you which Android you are running? Stock or customized? (e.g. Samsung UI, Xiaomi etc..)

![photo5823705547633964819](https://user-images.githubusercontent.com/32082962/142770268-7956c434-0dbc-4854-918b-f2134d49261b.jpg)
![photo5823705547633964818](https://user-images.githubusercontent.com/32082962/142770269-89a79848-94e5-490a-b45c-8f0395a637e0.jpg)
![photo5823705547633964817](https://user-images.githubusercontent.com/32082962/142770271-5a65e907-c54f-458c-a468-d8eb89e57057.jpg)

**Comment by eliasfloreteng** [comment]
I'm running a stock Samsung although only uxdesign and uxplanet are working for me. I just didn't try the others because the first one failed (silly of me). I will update the PR to only include towards data science, betterprogramming and plainenglish :)
